language: python

python: 3.7

matrix:

  include:
    - name: "Python on linux"
      os: linux
      addons:
        apt:
          packages:
            - gfortran
            - cmake
            - liblapack-dev
            - libblas-dev
            - libomp-dev
            - libopenmpi-dev
            - git

    - name: "Python on macOS (with libomp)"
      os: osx
      osx_image: xcode11
      language: shell
      addons:
        homebrew:
          packages:
            - cmake
            - gcc
            - python
            - libomp

    - name: "Python on macOS (without libomp)"
      os: osx
      osx_image: xcode11
      language: shell
      addons:
        homebrew:
          packages:
            - cmake
            - gcc
            - python


before_install:
  - |
    DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    git clone https://github.com/JohannesBuchner/MultiNest.git
    cd ${DEPS_DIR}/MultiNest/build && cmake .. && make && cd ${TRAVIS_BUILD_DIR}
    export LD_LIBRARY_PATH=${DEPS_DIR}/MultiNest/lib:${LD_LIBRARY_PATH}

install:
  - pip3 install cython scipy numpy matplotlib future pytest ipython
  - pip3 install -e .

script:
    - python check_env.py
    - pytest ./tests/
